version: '3'
services:
    face-recog-inference:
        build: .
        container_name: "face_recognition"
        image: ghcr.io/jainal09/face_recog:gpu
        command: uvicorn main:app --reload --host 0.0.0.0
        ports:
            - 7000:8000
        links:
            - mongodb
        depends_on:
            - mongodb
    mongodb:
        image: 'docker.io/bitnami/mongodb:4.4-debian-10'
        ports:
            - "27017:27017"
        volumes:
            - 'mongodb_data:/bitnami/mongodb'
        environment:
            - MONGODB_DISABLE_SYSTEM_LOG=true
    
volumes:
    mongodb_data:
        driver: local